# Generated by Django 3.2 on 2022-08-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_twitterprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterprofile',
            old_name='conment',
            new_name='comment',
        ),
    ]
