# Generated by Django 3.2 on 2022-08-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_conment_twitterprofile_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='username',
        ),
    ]
